/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing AddInterestReq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddInterestReqTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddInterestReq
        //private AddInterestReq instance;

        public AddInterestReqTests()
        {
            // TODO uncomment below to create an instance of AddInterestReq
            //instance = new AddInterestReq();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddInterestReq
        /// </summary>
        [Fact]
        public void AddInterestReqInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddInterestReq
            //Assert.IsType<AddInterestReq>(instance);
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

    }

}
