/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing AssistantListingRes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssistantListingResTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssistantListingRes
        //private AssistantListingRes instance;

        public AssistantListingResTests()
        {
            // TODO uncomment below to create an instance of AssistantListingRes
            //instance = new AssistantListingRes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssistantListingRes
        /// </summary>
        [Fact]
        public void AssistantListingResInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssistantListingRes
            //Assert.IsType<AssistantListingRes>(instance);
        }


        /// <summary>
        /// Test the property 'Assistants'
        /// </summary>
        [Fact]
        public void AssistantsTest()
        {
            // TODO unit test for the property 'Assistants'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
