/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing AssistantListingReq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssistantListingReqTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssistantListingReq
        //private AssistantListingReq instance;

        public AssistantListingReqTests()
        {
            // TODO uncomment below to create an instance of AssistantListingReq
            //instance = new AssistantListingReq();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssistantListingReq
        /// </summary>
        [Fact]
        public void AssistantListingReqInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssistantListingReq
            //Assert.IsType<AssistantListingReq>(instance);
        }


        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Search'
        /// </summary>
        [Fact]
        public void SearchTest()
        {
            // TODO unit test for the property 'Search'
        }
        /// <summary>
        /// Test the property 'Sort'
        /// </summary>
        [Fact]
        public void SortTest()
        {
            // TODO unit test for the property 'Sort'
        }

    }

}
