/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing CanBeAssistantRes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CanBeAssistantResTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CanBeAssistantRes
        //private CanBeAssistantRes instance;

        public CanBeAssistantResTests()
        {
            // TODO uncomment below to create an instance of CanBeAssistantRes
            //instance = new CanBeAssistantRes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CanBeAssistantRes
        /// </summary>
        [Fact]
        public void CanBeAssistantResInstanceTest()
        {
            // TODO uncomment below to test "IsType" CanBeAssistantRes
            //Assert.IsType<CanBeAssistantRes>(instance);
        }


        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }

    }

}
