/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing EmailPasswordLoginReq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailPasswordLoginReqTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailPasswordLoginReq
        //private EmailPasswordLoginReq instance;

        public EmailPasswordLoginReqTests()
        {
            // TODO uncomment below to create an instance of EmailPasswordLoginReq
            //instance = new EmailPasswordLoginReq();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailPasswordLoginReq
        /// </summary>
        [Fact]
        public void EmailPasswordLoginReqInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailPasswordLoginReq
            //Assert.IsType<EmailPasswordLoginReq>(instance);
        }


        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
