/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing GenderType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenderTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenderType
        //private GenderType instance;

        public GenderTypeTests()
        {
            // TODO uncomment below to create an instance of GenderType
            //instance = new GenderType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenderType
        /// </summary>
        [Fact]
        public void GenderTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenderType
            //Assert.IsType<GenderType>(instance);
        }



    }

}
