/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing HealthRes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HealthResTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HealthRes
        //private HealthRes instance;

        public HealthResTests()
        {
            // TODO uncomment below to create an instance of HealthRes
            //instance = new HealthRes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthRes
        /// </summary>
        [Fact]
        public void HealthResInstanceTest()
        {
            // TODO uncomment below to test "IsType" HealthRes
            //Assert.IsType<HealthRes>(instance);
        }


        /// <summary>
        /// Test the property 'Healthy'
        /// </summary>
        [Fact]
        public void HealthyTest()
        {
            // TODO unit test for the property 'Healthy'
        }

    }

}
