/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing LoginRes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoginResTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoginRes
        //private LoginRes instance;

        public LoginResTests()
        {
            // TODO uncomment below to create an instance of LoginRes
            //instance = new LoginRes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoginRes
        /// </summary>
        [Fact]
        public void LoginResInstanceTest()
        {
            // TODO uncomment below to test "IsType" LoginRes
            //Assert.IsType<LoginRes>(instance);
        }


        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [Fact]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }

    }

}
