/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing OtpRequestRes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OtpRequestResTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OtpRequestRes
        //private OtpRequestRes instance;

        public OtpRequestResTests()
        {
            // TODO uncomment below to create an instance of OtpRequestRes
            //instance = new OtpRequestRes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OtpRequestRes
        /// </summary>
        [Fact]
        public void OtpRequestResInstanceTest()
        {
            // TODO uncomment below to test "IsType" OtpRequestRes
            //Assert.IsType<OtpRequestRes>(instance);
        }


        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

    }

}
