/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing ProfileSettingDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProfileSettingDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProfileSettingDto
        //private ProfileSettingDto instance;

        public ProfileSettingDtoTests()
        {
            // TODO uncomment below to create an instance of ProfileSettingDto
            //instance = new ProfileSettingDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProfileSettingDto
        /// </summary>
        [Fact]
        public void ProfileSettingDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProfileSettingDto
            //Assert.IsType<ProfileSettingDto>(instance);
        }


        /// <summary>
        /// Test the property 'Available'
        /// </summary>
        [Fact]
        public void AvailableTest()
        {
            // TODO unit test for the property 'Available'
        }
        /// <summary>
        /// Test the property 'TimeIncludeFrom'
        /// </summary>
        [Fact]
        public void TimeIncludeFromTest()
        {
            // TODO unit test for the property 'TimeIncludeFrom'
        }
        /// <summary>
        /// Test the property 'TimeIncludeTo'
        /// </summary>
        [Fact]
        public void TimeIncludeToTest()
        {
            // TODO unit test for the property 'TimeIncludeTo'
        }
        /// <summary>
        /// Test the property 'DateExcludeFrom'
        /// </summary>
        [Fact]
        public void DateExcludeFromTest()
        {
            // TODO unit test for the property 'DateExcludeFrom'
        }
        /// <summary>
        /// Test the property 'DateExcludeTo'
        /// </summary>
        [Fact]
        public void DateExcludeToTest()
        {
            // TODO unit test for the property 'DateExcludeTo'
        }

    }

}
