/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing ValidateEmailReq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidateEmailReqTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValidateEmailReq
        //private ValidateEmailReq instance;

        public ValidateEmailReqTests()
        {
            // TODO uncomment below to create an instance of ValidateEmailReq
            //instance = new ValidateEmailReq();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValidateEmailReq
        /// </summary>
        [Fact]
        public void ValidateEmailReqInstanceTest()
        {
            // TODO uncomment below to test "IsType" ValidateEmailReq
            //Assert.IsType<ValidateEmailReq>(instance);
        }


        /// <summary>
        /// Test the property 'OtpToken'
        /// </summary>
        [Fact]
        public void OtpTokenTest()
        {
            // TODO unit test for the property 'OtpToken'
        }

    }

}
