/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing ValidateOtpUpdatePasswordReq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidateOtpUpdatePasswordReqTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValidateOtpUpdatePasswordReq
        //private ValidateOtpUpdatePasswordReq instance;

        public ValidateOtpUpdatePasswordReqTests()
        {
            // TODO uncomment below to create an instance of ValidateOtpUpdatePasswordReq
            //instance = new ValidateOtpUpdatePasswordReq();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValidateOtpUpdatePasswordReq
        /// </summary>
        [Fact]
        public void ValidateOtpUpdatePasswordReqInstanceTest()
        {
            // TODO uncomment below to test "IsType" ValidateOtpUpdatePasswordReq
            //Assert.IsType<ValidateOtpUpdatePasswordReq>(instance);
        }


        /// <summary>
        /// Test the property 'OtpToken'
        /// </summary>
        [Fact]
        public void OtpTokenTest()
        {
            // TODO unit test for the property 'OtpToken'
        }
        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Fact]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }

    }

}
