/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using profile.wire.Api;
using profile.wire.Model;
using profile.wire.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace profile.wire.Test.Model
{
    /// <summary>
    ///  Class for testing VerifyPhoneReq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifyPhoneReqTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifyPhoneReq
        //private VerifyPhoneReq instance;

        public VerifyPhoneReqTests()
        {
            // TODO uncomment below to create an instance of VerifyPhoneReq
            //instance = new VerifyPhoneReq();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifyPhoneReq
        /// </summary>
        [Fact]
        public void VerifyPhoneReqInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifyPhoneReq
            //Assert.IsType<VerifyPhoneReq>(instance);
        }


        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

    }

}
