/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using profile.wire.Client;
using profile.wire.Api;
// uncomment below to import models
//using profile.wire.Model;

namespace profile.wire.Test.Api
{
    /// <summary>
    ///  Class for testing AdminAuthApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AdminAuthApiTests : IDisposable
    {
        private AdminAuthApi instance;

        public AdminAuthApiTests()
        {
            instance = new AdminAuthApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminAuthApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AdminAuthApi
            //Assert.IsType<AdminAuthApi>(instance);
        }

        /// <summary>
        /// Test AdminAuthLoginPost
        /// </summary>
        [Fact]
        public void AdminAuthLoginPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EmailPasswordLoginReq? emailPasswordLoginReq = null;
            //var response = instance.AdminAuthLoginPost(emailPasswordLoginReq);
            //Assert.IsType<LoginRes>(response);
        }

        /// <summary>
        /// Test AdminAuthRefreshTokenPost
        /// </summary>
        [Fact]
        public void AdminAuthRefreshTokenPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RefreshTokenReq? refreshTokenReq = null;
            //var response = instance.AdminAuthRefreshTokenPost(refreshTokenReq);
            //Assert.IsType<LoginRes>(response);
        }
    }
}
