/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using profile.wire.Client;
using profile.wire.Api;
// uncomment below to import models
//using profile.wire.Model;

namespace profile.wire.Test.Api
{
    /// <summary>
    ///  Class for testing AssistantListingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AssistantListingApiTests : IDisposable
    {
        private AssistantListingApi instance;

        public AssistantListingApiTests()
        {
            instance = new AssistantListingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssistantListingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AssistantListingApi
            //Assert.IsType<AssistantListingApi>(instance);
        }

        /// <summary>
        /// Test AssistantListingListingPost
        /// </summary>
        [Fact]
        public void AssistantListingListingPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AssistantListingReq? assistantListingReq = null;
            //var response = instance.AssistantListingListingPost(assistantListingReq);
            //Assert.IsType<AssistantListingRes>(response);
        }

        /// <summary>
        /// Test AssistantListingUserListingPost
        /// </summary>
        [Fact]
        public void AssistantListingUserListingPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AssistantListingReq? assistantListingReq = null;
            //var response = instance.AssistantListingUserListingPost(assistantListingReq);
            //Assert.IsType<AssistantListingRes>(response);
        }
    }
}
