/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using profile.wire.Client;
using profile.wire.Api;
// uncomment below to import models
//using profile.wire.Model;

namespace profile.wire.Test.Api
{
    /// <summary>
    ///  Class for testing HealthApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class HealthApiTests : IDisposable
    {
        private HealthApi instance;

        public HealthApiTests()
        {
            instance = new HealthApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' HealthApi
            //Assert.IsType<HealthApi>(instance);
        }

        /// <summary>
        /// Test HealthGet
        /// </summary>
        [Fact]
        public void HealthGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.HealthGet();
            //Assert.IsType<HealthRes>(response);
        }
    }
}
