/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using profile.wire.Client;
using profile.wire.Api;
// uncomment below to import models
//using profile.wire.Model;

namespace profile.wire.Test.Api
{
    /// <summary>
    ///  Class for testing ProfileSettingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProfileSettingApiTests : IDisposable
    {
        private ProfileSettingApi instance;

        public ProfileSettingApiTests()
        {
            instance = new ProfileSettingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProfileSettingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProfileSettingApi
            //Assert.IsType<ProfileSettingApi>(instance);
        }

        /// <summary>
        /// Test ProfileSettingUpdateProfileSettingPatch
        /// </summary>
        [Fact]
        public void ProfileSettingUpdateProfileSettingPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateProfileSettingReq? updateProfileSettingReq = null;
            //var response = instance.ProfileSettingUpdateProfileSettingPatch(updateProfileSettingReq);
            //Assert.IsType<EmptyResponse>(response);
        }
    }
}
