/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = profile.wire.Client.OpenAPIDateConverter;

namespace profile.wire.Model
{
    /// <summary>
    /// AssistantListingRes
    /// </summary>
    [DataContract(Name = "AssistantListingRes")]
    public partial class AssistantListingRes : IEquatable<AssistantListingRes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssistantListingRes" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AssistantListingRes() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AssistantListingRes" /> class.
        /// </summary>
        /// <param name="assistants">assistants.</param>
        /// <param name="total">total (required).</param>
        public AssistantListingRes(List<AssistantListItem> assistants = default(List<AssistantListItem>), long total = default(long))
        {
            this.Total = total;
            this.Assistants = assistants;
        }

        /// <summary>
        /// Gets or Sets Assistants
        /// </summary>
        [DataMember(Name = "assistants", EmitDefaultValue = true)]
        public List<AssistantListItem> Assistants { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public long Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AssistantListingRes {\n");
            sb.Append("  Assistants: ").Append(Assistants).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AssistantListingRes);
        }

        /// <summary>
        /// Returns true if AssistantListingRes instances are equal
        /// </summary>
        /// <param name="input">Instance of AssistantListingRes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssistantListingRes input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Assistants == input.Assistants ||
                    this.Assistants != null &&
                    input.Assistants != null &&
                    this.Assistants.SequenceEqual(input.Assistants)
                ) && 
                (
                    this.Total == input.Total ||
                    this.Total.Equals(input.Total)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Assistants != null)
                {
                    hashCode = (hashCode * 59) + this.Assistants.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Total.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
