/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = profile.wire.Client.OpenAPIDateConverter;

namespace profile.wire.Model
{
    /// <summary>
    /// UpdateInterestsReq
    /// </summary>
    [DataContract(Name = "UpdateInterestsReq")]
    public partial class UpdateInterestsReq : IEquatable<UpdateInterestsReq>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateInterestsReq" /> class.
        /// </summary>
        /// <param name="interestKeys">interestKeys.</param>
        public UpdateInterestsReq(List<string> interestKeys = default(List<string>))
        {
            this.InterestKeys = interestKeys;
        }

        /// <summary>
        /// Gets or Sets InterestKeys
        /// </summary>
        [DataMember(Name = "interestKeys", EmitDefaultValue = true)]
        public List<string> InterestKeys { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateInterestsReq {\n");
            sb.Append("  InterestKeys: ").Append(InterestKeys).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateInterestsReq);
        }

        /// <summary>
        /// Returns true if UpdateInterestsReq instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateInterestsReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateInterestsReq input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.InterestKeys == input.InterestKeys ||
                    this.InterestKeys != null &&
                    input.InterestKeys != null &&
                    this.InterestKeys.SequenceEqual(input.InterestKeys)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InterestKeys != null)
                {
                    hashCode = (hashCode * 59) + this.InterestKeys.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
