/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = profile.wire.Client.OpenAPIDateConverter;

namespace profile.wire.Model
{
    /// <summary>
    /// ValidateOtpUpdatePasswordReq
    /// </summary>
    [DataContract(Name = "ValidateOtpUpdatePasswordReq")]
    public partial class ValidateOtpUpdatePasswordReq : IEquatable<ValidateOtpUpdatePasswordReq>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidateOtpUpdatePasswordReq" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ValidateOtpUpdatePasswordReq() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidateOtpUpdatePasswordReq" /> class.
        /// </summary>
        /// <param name="otpToken">otpToken (required).</param>
        /// <param name="newPassword">newPassword (required).</param>
        public ValidateOtpUpdatePasswordReq(string otpToken = default(string), string newPassword = default(string))
        {
            // to ensure "otpToken" is required (not null)
            if (otpToken == null)
            {
                throw new ArgumentNullException("otpToken is a required property for ValidateOtpUpdatePasswordReq and cannot be null");
            }
            this.OtpToken = otpToken;
            // to ensure "newPassword" is required (not null)
            if (newPassword == null)
            {
                throw new ArgumentNullException("newPassword is a required property for ValidateOtpUpdatePasswordReq and cannot be null");
            }
            this.NewPassword = newPassword;
        }

        /// <summary>
        /// Gets or Sets OtpToken
        /// </summary>
        [DataMember(Name = "otpToken", IsRequired = true, EmitDefaultValue = true)]
        public string OtpToken { get; set; }

        /// <summary>
        /// Gets or Sets NewPassword
        /// </summary>
        [DataMember(Name = "newPassword", IsRequired = true, EmitDefaultValue = true)]
        public string NewPassword { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidateOtpUpdatePasswordReq {\n");
            sb.Append("  OtpToken: ").Append(OtpToken).Append("\n");
            sb.Append("  NewPassword: ").Append(NewPassword).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ValidateOtpUpdatePasswordReq);
        }

        /// <summary>
        /// Returns true if ValidateOtpUpdatePasswordReq instances are equal
        /// </summary>
        /// <param name="input">Instance of ValidateOtpUpdatePasswordReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValidateOtpUpdatePasswordReq input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.OtpToken == input.OtpToken ||
                    (this.OtpToken != null &&
                    this.OtpToken.Equals(input.OtpToken))
                ) && 
                (
                    this.NewPassword == input.NewPassword ||
                    (this.NewPassword != null &&
                    this.NewPassword.Equals(input.NewPassword))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OtpToken != null)
                {
                    hashCode = (hashCode * 59) + this.OtpToken.GetHashCode();
                }
                if (this.NewPassword != null)
                {
                    hashCode = (hashCode * 59) + this.NewPassword.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // NewPassword (string) minLength
            if (this.NewPassword != null && this.NewPassword.Length < 8)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NewPassword, length must be greater than 8.", new [] { "NewPassword" });
            }

            yield break;
        }
    }

}
