/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = profile.wire.Client.OpenAPIDateConverter;

namespace profile.wire.Model
{
    /// <summary>
    /// ValidateEmailReq
    /// </summary>
    [DataContract(Name = "ValidateEmailReq")]
    public partial class ValidateEmailReq : IEquatable<ValidateEmailReq>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidateEmailReq" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ValidateEmailReq() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidateEmailReq" /> class.
        /// </summary>
        /// <param name="otpToken">otpToken (required).</param>
        public ValidateEmailReq(string otpToken = default(string))
        {
            // to ensure "otpToken" is required (not null)
            if (otpToken == null)
            {
                throw new ArgumentNullException("otpToken is a required property for ValidateEmailReq and cannot be null");
            }
            this.OtpToken = otpToken;
        }

        /// <summary>
        /// Gets or Sets OtpToken
        /// </summary>
        [DataMember(Name = "otpToken", IsRequired = true, EmitDefaultValue = true)]
        public string OtpToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidateEmailReq {\n");
            sb.Append("  OtpToken: ").Append(OtpToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ValidateEmailReq);
        }

        /// <summary>
        /// Returns true if ValidateEmailReq instances are equal
        /// </summary>
        /// <param name="input">Instance of ValidateEmailReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValidateEmailReq input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.OtpToken == input.OtpToken ||
                    (this.OtpToken != null &&
                    this.OtpToken.Equals(input.OtpToken))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OtpToken != null)
                {
                    hashCode = (hashCode * 59) + this.OtpToken.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
