/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using profile.wire.Client;
using profile.wire.Model;

namespace profile.wire.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProfileSecurityApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OtpForgetPasswordRes</returns>
        OtpForgetPasswordRes ProfileSecurityUpdatePasswordOtpRequestPost(int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OtpForgetPasswordRes</returns>
        ApiResponse<OtpForgetPasswordRes> ProfileSecurityUpdatePasswordOtpRequestPostWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validateOtpUpdatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EmptyResponse</returns>
        EmptyResponse ProfileSecurityUpdatePasswordOtpVerifyPatch(ValidateOtpUpdatePasswordReq? validateOtpUpdatePasswordReq = default(ValidateOtpUpdatePasswordReq?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validateOtpUpdatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EmptyResponse</returns>
        ApiResponse<EmptyResponse> ProfileSecurityUpdatePasswordOtpVerifyPatchWithHttpInfo(ValidateOtpUpdatePasswordReq? validateOtpUpdatePasswordReq = default(ValidateOtpUpdatePasswordReq?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EmptyResponse</returns>
        EmptyResponse ProfileSecurityUpdatePasswordPatch(UpdatePasswordReq? updatePasswordReq = default(UpdatePasswordReq?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EmptyResponse</returns>
        ApiResponse<EmptyResponse> ProfileSecurityUpdatePasswordPatchWithHttpInfo(UpdatePasswordReq? updatePasswordReq = default(UpdatePasswordReq?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyPhoneReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>VerifyPhoneRes</returns>
        VerifyPhoneRes ProfileSecurityUpdatePhoneRequestPost(VerifyPhoneReq? verifyPhoneReq = default(VerifyPhoneReq?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyPhoneReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of VerifyPhoneRes</returns>
        ApiResponse<VerifyPhoneRes> ProfileSecurityUpdatePhoneRequestPostWithHttpInfo(VerifyPhoneReq? verifyPhoneReq = default(VerifyPhoneReq?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validatePhoneVerificationReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EmptyResponse</returns>
        EmptyResponse ProfileSecurityUpdatePhoneVerifyPatch(ValidatePhoneVerificationReq? validatePhoneVerificationReq = default(ValidatePhoneVerificationReq?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validatePhoneVerificationReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EmptyResponse</returns>
        ApiResponse<EmptyResponse> ProfileSecurityUpdatePhoneVerifyPatchWithHttpInfo(ValidatePhoneVerificationReq? validatePhoneVerificationReq = default(ValidatePhoneVerificationReq?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProfileSecurityApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OtpForgetPasswordRes</returns>
        System.Threading.Tasks.Task<OtpForgetPasswordRes> ProfileSecurityUpdatePasswordOtpRequestPostAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OtpForgetPasswordRes)</returns>
        System.Threading.Tasks.Task<ApiResponse<OtpForgetPasswordRes>> ProfileSecurityUpdatePasswordOtpRequestPostWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validateOtpUpdatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EmptyResponse</returns>
        System.Threading.Tasks.Task<EmptyResponse> ProfileSecurityUpdatePasswordOtpVerifyPatchAsync(ValidateOtpUpdatePasswordReq? validateOtpUpdatePasswordReq = default(ValidateOtpUpdatePasswordReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validateOtpUpdatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EmptyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<EmptyResponse>> ProfileSecurityUpdatePasswordOtpVerifyPatchWithHttpInfoAsync(ValidateOtpUpdatePasswordReq? validateOtpUpdatePasswordReq = default(ValidateOtpUpdatePasswordReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EmptyResponse</returns>
        System.Threading.Tasks.Task<EmptyResponse> ProfileSecurityUpdatePasswordPatchAsync(UpdatePasswordReq? updatePasswordReq = default(UpdatePasswordReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EmptyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<EmptyResponse>> ProfileSecurityUpdatePasswordPatchWithHttpInfoAsync(UpdatePasswordReq? updatePasswordReq = default(UpdatePasswordReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyPhoneReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of VerifyPhoneRes</returns>
        System.Threading.Tasks.Task<VerifyPhoneRes> ProfileSecurityUpdatePhoneRequestPostAsync(VerifyPhoneReq? verifyPhoneReq = default(VerifyPhoneReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyPhoneReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (VerifyPhoneRes)</returns>
        System.Threading.Tasks.Task<ApiResponse<VerifyPhoneRes>> ProfileSecurityUpdatePhoneRequestPostWithHttpInfoAsync(VerifyPhoneReq? verifyPhoneReq = default(VerifyPhoneReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validatePhoneVerificationReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EmptyResponse</returns>
        System.Threading.Tasks.Task<EmptyResponse> ProfileSecurityUpdatePhoneVerifyPatchAsync(ValidatePhoneVerificationReq? validatePhoneVerificationReq = default(ValidatePhoneVerificationReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validatePhoneVerificationReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EmptyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<EmptyResponse>> ProfileSecurityUpdatePhoneVerifyPatchWithHttpInfoAsync(ValidatePhoneVerificationReq? validatePhoneVerificationReq = default(ValidatePhoneVerificationReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProfileSecurityApi : IProfileSecurityApiSync, IProfileSecurityApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ProfileSecurityApi : IProfileSecurityApi
    {
        private profile.wire.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileSecurityApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProfileSecurityApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileSecurityApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProfileSecurityApi(string basePath)
        {
            this.Configuration = profile.wire.Client.Configuration.MergeConfigurations(
                profile.wire.Client.GlobalConfiguration.Instance,
                new profile.wire.Client.Configuration { BasePath = basePath }
            );
            this.Client = new profile.wire.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new profile.wire.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = profile.wire.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileSecurityApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ProfileSecurityApi(profile.wire.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = profile.wire.Client.Configuration.MergeConfigurations(
                profile.wire.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new profile.wire.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new profile.wire.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = profile.wire.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileSecurityApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ProfileSecurityApi(profile.wire.Client.ISynchronousClient client, profile.wire.Client.IAsynchronousClient asyncClient, profile.wire.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = profile.wire.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public profile.wire.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public profile.wire.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public profile.wire.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public profile.wire.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OtpForgetPasswordRes</returns>
        public OtpForgetPasswordRes ProfileSecurityUpdatePasswordOtpRequestPost(int operationIndex = 0)
        {
            profile.wire.Client.ApiResponse<OtpForgetPasswordRes> localVarResponse = ProfileSecurityUpdatePasswordOtpRequestPostWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OtpForgetPasswordRes</returns>
        public profile.wire.Client.ApiResponse<OtpForgetPasswordRes> ProfileSecurityUpdatePasswordOtpRequestPostWithHttpInfo(int operationIndex = 0)
        {
            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ProfileSecurityApi.ProfileSecurityUpdatePasswordOtpRequestPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<OtpForgetPasswordRes>("/ProfileSecurity/UpdatePasswordOtpRequest", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProfileSecurityUpdatePasswordOtpRequestPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OtpForgetPasswordRes</returns>
        public async System.Threading.Tasks.Task<OtpForgetPasswordRes> ProfileSecurityUpdatePasswordOtpRequestPostAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            profile.wire.Client.ApiResponse<OtpForgetPasswordRes> localVarResponse = await ProfileSecurityUpdatePasswordOtpRequestPostWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OtpForgetPasswordRes)</returns>
        public async System.Threading.Tasks.Task<profile.wire.Client.ApiResponse<OtpForgetPasswordRes>> ProfileSecurityUpdatePasswordOtpRequestPostWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ProfileSecurityApi.ProfileSecurityUpdatePasswordOtpRequestPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<OtpForgetPasswordRes>("/ProfileSecurity/UpdatePasswordOtpRequest", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProfileSecurityUpdatePasswordOtpRequestPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validateOtpUpdatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EmptyResponse</returns>
        public EmptyResponse ProfileSecurityUpdatePasswordOtpVerifyPatch(ValidateOtpUpdatePasswordReq? validateOtpUpdatePasswordReq = default(ValidateOtpUpdatePasswordReq?), int operationIndex = 0)
        {
            profile.wire.Client.ApiResponse<EmptyResponse> localVarResponse = ProfileSecurityUpdatePasswordOtpVerifyPatchWithHttpInfo(validateOtpUpdatePasswordReq);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validateOtpUpdatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EmptyResponse</returns>
        public profile.wire.Client.ApiResponse<EmptyResponse> ProfileSecurityUpdatePasswordOtpVerifyPatchWithHttpInfo(ValidateOtpUpdatePasswordReq? validateOtpUpdatePasswordReq = default(ValidateOtpUpdatePasswordReq?), int operationIndex = 0)
        {
            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = validateOtpUpdatePasswordReq;

            localVarRequestOptions.Operation = "ProfileSecurityApi.ProfileSecurityUpdatePasswordOtpVerifyPatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<EmptyResponse>("/ProfileSecurity/UpdatePasswordOtpVerify", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProfileSecurityUpdatePasswordOtpVerifyPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validateOtpUpdatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EmptyResponse</returns>
        public async System.Threading.Tasks.Task<EmptyResponse> ProfileSecurityUpdatePasswordOtpVerifyPatchAsync(ValidateOtpUpdatePasswordReq? validateOtpUpdatePasswordReq = default(ValidateOtpUpdatePasswordReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            profile.wire.Client.ApiResponse<EmptyResponse> localVarResponse = await ProfileSecurityUpdatePasswordOtpVerifyPatchWithHttpInfoAsync(validateOtpUpdatePasswordReq, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validateOtpUpdatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EmptyResponse)</returns>
        public async System.Threading.Tasks.Task<profile.wire.Client.ApiResponse<EmptyResponse>> ProfileSecurityUpdatePasswordOtpVerifyPatchWithHttpInfoAsync(ValidateOtpUpdatePasswordReq? validateOtpUpdatePasswordReq = default(ValidateOtpUpdatePasswordReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = validateOtpUpdatePasswordReq;

            localVarRequestOptions.Operation = "ProfileSecurityApi.ProfileSecurityUpdatePasswordOtpVerifyPatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<EmptyResponse>("/ProfileSecurity/UpdatePasswordOtpVerify", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProfileSecurityUpdatePasswordOtpVerifyPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EmptyResponse</returns>
        public EmptyResponse ProfileSecurityUpdatePasswordPatch(UpdatePasswordReq? updatePasswordReq = default(UpdatePasswordReq?), int operationIndex = 0)
        {
            profile.wire.Client.ApiResponse<EmptyResponse> localVarResponse = ProfileSecurityUpdatePasswordPatchWithHttpInfo(updatePasswordReq);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EmptyResponse</returns>
        public profile.wire.Client.ApiResponse<EmptyResponse> ProfileSecurityUpdatePasswordPatchWithHttpInfo(UpdatePasswordReq? updatePasswordReq = default(UpdatePasswordReq?), int operationIndex = 0)
        {
            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = updatePasswordReq;

            localVarRequestOptions.Operation = "ProfileSecurityApi.ProfileSecurityUpdatePasswordPatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<EmptyResponse>("/ProfileSecurity/UpdatePassword", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProfileSecurityUpdatePasswordPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EmptyResponse</returns>
        public async System.Threading.Tasks.Task<EmptyResponse> ProfileSecurityUpdatePasswordPatchAsync(UpdatePasswordReq? updatePasswordReq = default(UpdatePasswordReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            profile.wire.Client.ApiResponse<EmptyResponse> localVarResponse = await ProfileSecurityUpdatePasswordPatchWithHttpInfoAsync(updatePasswordReq, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="updatePasswordReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EmptyResponse)</returns>
        public async System.Threading.Tasks.Task<profile.wire.Client.ApiResponse<EmptyResponse>> ProfileSecurityUpdatePasswordPatchWithHttpInfoAsync(UpdatePasswordReq? updatePasswordReq = default(UpdatePasswordReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = updatePasswordReq;

            localVarRequestOptions.Operation = "ProfileSecurityApi.ProfileSecurityUpdatePasswordPatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<EmptyResponse>("/ProfileSecurity/UpdatePassword", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProfileSecurityUpdatePasswordPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyPhoneReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>VerifyPhoneRes</returns>
        public VerifyPhoneRes ProfileSecurityUpdatePhoneRequestPost(VerifyPhoneReq? verifyPhoneReq = default(VerifyPhoneReq?), int operationIndex = 0)
        {
            profile.wire.Client.ApiResponse<VerifyPhoneRes> localVarResponse = ProfileSecurityUpdatePhoneRequestPostWithHttpInfo(verifyPhoneReq);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyPhoneReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of VerifyPhoneRes</returns>
        public profile.wire.Client.ApiResponse<VerifyPhoneRes> ProfileSecurityUpdatePhoneRequestPostWithHttpInfo(VerifyPhoneReq? verifyPhoneReq = default(VerifyPhoneReq?), int operationIndex = 0)
        {
            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = verifyPhoneReq;

            localVarRequestOptions.Operation = "ProfileSecurityApi.ProfileSecurityUpdatePhoneRequestPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<VerifyPhoneRes>("/ProfileSecurity/UpdatePhoneRequest", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProfileSecurityUpdatePhoneRequestPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyPhoneReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of VerifyPhoneRes</returns>
        public async System.Threading.Tasks.Task<VerifyPhoneRes> ProfileSecurityUpdatePhoneRequestPostAsync(VerifyPhoneReq? verifyPhoneReq = default(VerifyPhoneReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            profile.wire.Client.ApiResponse<VerifyPhoneRes> localVarResponse = await ProfileSecurityUpdatePhoneRequestPostWithHttpInfoAsync(verifyPhoneReq, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="verifyPhoneReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (VerifyPhoneRes)</returns>
        public async System.Threading.Tasks.Task<profile.wire.Client.ApiResponse<VerifyPhoneRes>> ProfileSecurityUpdatePhoneRequestPostWithHttpInfoAsync(VerifyPhoneReq? verifyPhoneReq = default(VerifyPhoneReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = verifyPhoneReq;

            localVarRequestOptions.Operation = "ProfileSecurityApi.ProfileSecurityUpdatePhoneRequestPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<VerifyPhoneRes>("/ProfileSecurity/UpdatePhoneRequest", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProfileSecurityUpdatePhoneRequestPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validatePhoneVerificationReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EmptyResponse</returns>
        public EmptyResponse ProfileSecurityUpdatePhoneVerifyPatch(ValidatePhoneVerificationReq? validatePhoneVerificationReq = default(ValidatePhoneVerificationReq?), int operationIndex = 0)
        {
            profile.wire.Client.ApiResponse<EmptyResponse> localVarResponse = ProfileSecurityUpdatePhoneVerifyPatchWithHttpInfo(validatePhoneVerificationReq);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validatePhoneVerificationReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EmptyResponse</returns>
        public profile.wire.Client.ApiResponse<EmptyResponse> ProfileSecurityUpdatePhoneVerifyPatchWithHttpInfo(ValidatePhoneVerificationReq? validatePhoneVerificationReq = default(ValidatePhoneVerificationReq?), int operationIndex = 0)
        {
            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = validatePhoneVerificationReq;

            localVarRequestOptions.Operation = "ProfileSecurityApi.ProfileSecurityUpdatePhoneVerifyPatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<EmptyResponse>("/ProfileSecurity/UpdatePhoneVerify", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProfileSecurityUpdatePhoneVerifyPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validatePhoneVerificationReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EmptyResponse</returns>
        public async System.Threading.Tasks.Task<EmptyResponse> ProfileSecurityUpdatePhoneVerifyPatchAsync(ValidatePhoneVerificationReq? validatePhoneVerificationReq = default(ValidatePhoneVerificationReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            profile.wire.Client.ApiResponse<EmptyResponse> localVarResponse = await ProfileSecurityUpdatePhoneVerifyPatchWithHttpInfoAsync(validatePhoneVerificationReq, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="validatePhoneVerificationReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EmptyResponse)</returns>
        public async System.Threading.Tasks.Task<profile.wire.Client.ApiResponse<EmptyResponse>> ProfileSecurityUpdatePhoneVerifyPatchWithHttpInfoAsync(ValidatePhoneVerificationReq? validatePhoneVerificationReq = default(ValidatePhoneVerificationReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = validatePhoneVerificationReq;

            localVarRequestOptions.Operation = "ProfileSecurityApi.ProfileSecurityUpdatePhoneVerifyPatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<EmptyResponse>("/ProfileSecurity/UpdatePhoneVerify", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ProfileSecurityUpdatePhoneVerifyPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
