/*
 * TP.Profile.Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using profile.wire.Client;
using profile.wire.Model;

namespace profile.wire.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserAuthApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LoginRes</returns>
        LoginRes UserAuthGoogleLoginPost(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LoginRes</returns>
        ApiResponse<LoginRes> UserAuthGoogleLoginPostWithHttpInfo(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emailPasswordLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LoginRes</returns>
        LoginRes UserAuthLoginPost(EmailPasswordLoginReq? emailPasswordLoginReq = default(EmailPasswordLoginReq?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emailPasswordLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LoginRes</returns>
        ApiResponse<LoginRes> UserAuthLoginPostWithHttpInfo(EmailPasswordLoginReq? emailPasswordLoginReq = default(EmailPasswordLoginReq?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OtpRequestRes</returns>
        OtpRequestRes UserAuthOtpLoginRequestPost(OtpLoginReq? otpLoginReq = default(OtpLoginReq?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OtpRequestRes</returns>
        ApiResponse<OtpRequestRes> UserAuthOtpLoginRequestPostWithHttpInfo(OtpLoginReq? otpLoginReq = default(OtpLoginReq?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginValidateReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LoginRes</returns>
        LoginRes UserAuthOtpLoginValidatePost(OtpLoginValidateReq? otpLoginValidateReq = default(OtpLoginValidateReq?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginValidateReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LoginRes</returns>
        ApiResponse<LoginRes> UserAuthOtpLoginValidatePostWithHttpInfo(OtpLoginValidateReq? otpLoginValidateReq = default(OtpLoginValidateReq?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LoginRes</returns>
        LoginRes UserAuthRefreshTokenPost(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LoginRes</returns>
        ApiResponse<LoginRes> UserAuthRefreshTokenPostWithHttpInfo(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userRegisterReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LoginRes</returns>
        LoginRes UserAuthRegisterPost(UserRegisterReq? userRegisterReq = default(UserRegisterReq?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userRegisterReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LoginRes</returns>
        ApiResponse<LoginRes> UserAuthRegisterPostWithHttpInfo(UserRegisterReq? userRegisterReq = default(UserRegisterReq?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserAuthApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginRes</returns>
        System.Threading.Tasks.Task<LoginRes> UserAuthGoogleLoginPostAsync(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginRes)</returns>
        System.Threading.Tasks.Task<ApiResponse<LoginRes>> UserAuthGoogleLoginPostWithHttpInfoAsync(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emailPasswordLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginRes</returns>
        System.Threading.Tasks.Task<LoginRes> UserAuthLoginPostAsync(EmailPasswordLoginReq? emailPasswordLoginReq = default(EmailPasswordLoginReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emailPasswordLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginRes)</returns>
        System.Threading.Tasks.Task<ApiResponse<LoginRes>> UserAuthLoginPostWithHttpInfoAsync(EmailPasswordLoginReq? emailPasswordLoginReq = default(EmailPasswordLoginReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OtpRequestRes</returns>
        System.Threading.Tasks.Task<OtpRequestRes> UserAuthOtpLoginRequestPostAsync(OtpLoginReq? otpLoginReq = default(OtpLoginReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OtpRequestRes)</returns>
        System.Threading.Tasks.Task<ApiResponse<OtpRequestRes>> UserAuthOtpLoginRequestPostWithHttpInfoAsync(OtpLoginReq? otpLoginReq = default(OtpLoginReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginValidateReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginRes</returns>
        System.Threading.Tasks.Task<LoginRes> UserAuthOtpLoginValidatePostAsync(OtpLoginValidateReq? otpLoginValidateReq = default(OtpLoginValidateReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginValidateReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginRes)</returns>
        System.Threading.Tasks.Task<ApiResponse<LoginRes>> UserAuthOtpLoginValidatePostWithHttpInfoAsync(OtpLoginValidateReq? otpLoginValidateReq = default(OtpLoginValidateReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginRes</returns>
        System.Threading.Tasks.Task<LoginRes> UserAuthRefreshTokenPostAsync(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginRes)</returns>
        System.Threading.Tasks.Task<ApiResponse<LoginRes>> UserAuthRefreshTokenPostWithHttpInfoAsync(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userRegisterReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginRes</returns>
        System.Threading.Tasks.Task<LoginRes> UserAuthRegisterPostAsync(UserRegisterReq? userRegisterReq = default(UserRegisterReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userRegisterReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginRes)</returns>
        System.Threading.Tasks.Task<ApiResponse<LoginRes>> UserAuthRegisterPostWithHttpInfoAsync(UserRegisterReq? userRegisterReq = default(UserRegisterReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserAuthApi : IUserAuthApiSync, IUserAuthApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UserAuthApi : IUserAuthApi
    {
        private profile.wire.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserAuthApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserAuthApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserAuthApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserAuthApi(string basePath)
        {
            this.Configuration = profile.wire.Client.Configuration.MergeConfigurations(
                profile.wire.Client.GlobalConfiguration.Instance,
                new profile.wire.Client.Configuration { BasePath = basePath }
            );
            this.Client = new profile.wire.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new profile.wire.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = profile.wire.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserAuthApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UserAuthApi(profile.wire.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = profile.wire.Client.Configuration.MergeConfigurations(
                profile.wire.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new profile.wire.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new profile.wire.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = profile.wire.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserAuthApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public UserAuthApi(profile.wire.Client.ISynchronousClient client, profile.wire.Client.IAsynchronousClient asyncClient, profile.wire.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = profile.wire.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public profile.wire.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public profile.wire.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public profile.wire.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public profile.wire.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LoginRes</returns>
        public LoginRes UserAuthGoogleLoginPost(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0)
        {
            profile.wire.Client.ApiResponse<LoginRes> localVarResponse = UserAuthGoogleLoginPostWithHttpInfo(refreshTokenReq);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LoginRes</returns>
        public profile.wire.Client.ApiResponse<LoginRes> UserAuthGoogleLoginPostWithHttpInfo(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0)
        {
            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = refreshTokenReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthGoogleLoginPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LoginRes>("/UserAuth/GoogleLogin", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthGoogleLoginPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginRes</returns>
        public async System.Threading.Tasks.Task<LoginRes> UserAuthGoogleLoginPostAsync(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            profile.wire.Client.ApiResponse<LoginRes> localVarResponse = await UserAuthGoogleLoginPostWithHttpInfoAsync(refreshTokenReq, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginRes)</returns>
        public async System.Threading.Tasks.Task<profile.wire.Client.ApiResponse<LoginRes>> UserAuthGoogleLoginPostWithHttpInfoAsync(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = refreshTokenReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthGoogleLoginPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<LoginRes>("/UserAuth/GoogleLogin", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthGoogleLoginPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emailPasswordLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LoginRes</returns>
        public LoginRes UserAuthLoginPost(EmailPasswordLoginReq? emailPasswordLoginReq = default(EmailPasswordLoginReq?), int operationIndex = 0)
        {
            profile.wire.Client.ApiResponse<LoginRes> localVarResponse = UserAuthLoginPostWithHttpInfo(emailPasswordLoginReq);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emailPasswordLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LoginRes</returns>
        public profile.wire.Client.ApiResponse<LoginRes> UserAuthLoginPostWithHttpInfo(EmailPasswordLoginReq? emailPasswordLoginReq = default(EmailPasswordLoginReq?), int operationIndex = 0)
        {
            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = emailPasswordLoginReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthLoginPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LoginRes>("/UserAuth/Login", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthLoginPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emailPasswordLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginRes</returns>
        public async System.Threading.Tasks.Task<LoginRes> UserAuthLoginPostAsync(EmailPasswordLoginReq? emailPasswordLoginReq = default(EmailPasswordLoginReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            profile.wire.Client.ApiResponse<LoginRes> localVarResponse = await UserAuthLoginPostWithHttpInfoAsync(emailPasswordLoginReq, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emailPasswordLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginRes)</returns>
        public async System.Threading.Tasks.Task<profile.wire.Client.ApiResponse<LoginRes>> UserAuthLoginPostWithHttpInfoAsync(EmailPasswordLoginReq? emailPasswordLoginReq = default(EmailPasswordLoginReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = emailPasswordLoginReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthLoginPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<LoginRes>("/UserAuth/Login", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthLoginPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OtpRequestRes</returns>
        public OtpRequestRes UserAuthOtpLoginRequestPost(OtpLoginReq? otpLoginReq = default(OtpLoginReq?), int operationIndex = 0)
        {
            profile.wire.Client.ApiResponse<OtpRequestRes> localVarResponse = UserAuthOtpLoginRequestPostWithHttpInfo(otpLoginReq);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OtpRequestRes</returns>
        public profile.wire.Client.ApiResponse<OtpRequestRes> UserAuthOtpLoginRequestPostWithHttpInfo(OtpLoginReq? otpLoginReq = default(OtpLoginReq?), int operationIndex = 0)
        {
            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = otpLoginReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthOtpLoginRequestPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<OtpRequestRes>("/UserAuth/OtpLoginRequest", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthOtpLoginRequestPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OtpRequestRes</returns>
        public async System.Threading.Tasks.Task<OtpRequestRes> UserAuthOtpLoginRequestPostAsync(OtpLoginReq? otpLoginReq = default(OtpLoginReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            profile.wire.Client.ApiResponse<OtpRequestRes> localVarResponse = await UserAuthOtpLoginRequestPostWithHttpInfoAsync(otpLoginReq, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OtpRequestRes)</returns>
        public async System.Threading.Tasks.Task<profile.wire.Client.ApiResponse<OtpRequestRes>> UserAuthOtpLoginRequestPostWithHttpInfoAsync(OtpLoginReq? otpLoginReq = default(OtpLoginReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = otpLoginReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthOtpLoginRequestPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<OtpRequestRes>("/UserAuth/OtpLoginRequest", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthOtpLoginRequestPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginValidateReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LoginRes</returns>
        public LoginRes UserAuthOtpLoginValidatePost(OtpLoginValidateReq? otpLoginValidateReq = default(OtpLoginValidateReq?), int operationIndex = 0)
        {
            profile.wire.Client.ApiResponse<LoginRes> localVarResponse = UserAuthOtpLoginValidatePostWithHttpInfo(otpLoginValidateReq);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginValidateReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LoginRes</returns>
        public profile.wire.Client.ApiResponse<LoginRes> UserAuthOtpLoginValidatePostWithHttpInfo(OtpLoginValidateReq? otpLoginValidateReq = default(OtpLoginValidateReq?), int operationIndex = 0)
        {
            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = otpLoginValidateReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthOtpLoginValidatePost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LoginRes>("/UserAuth/OtpLoginValidate", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthOtpLoginValidatePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginValidateReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginRes</returns>
        public async System.Threading.Tasks.Task<LoginRes> UserAuthOtpLoginValidatePostAsync(OtpLoginValidateReq? otpLoginValidateReq = default(OtpLoginValidateReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            profile.wire.Client.ApiResponse<LoginRes> localVarResponse = await UserAuthOtpLoginValidatePostWithHttpInfoAsync(otpLoginValidateReq, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otpLoginValidateReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginRes)</returns>
        public async System.Threading.Tasks.Task<profile.wire.Client.ApiResponse<LoginRes>> UserAuthOtpLoginValidatePostWithHttpInfoAsync(OtpLoginValidateReq? otpLoginValidateReq = default(OtpLoginValidateReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = otpLoginValidateReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthOtpLoginValidatePost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<LoginRes>("/UserAuth/OtpLoginValidate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthOtpLoginValidatePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LoginRes</returns>
        public LoginRes UserAuthRefreshTokenPost(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0)
        {
            profile.wire.Client.ApiResponse<LoginRes> localVarResponse = UserAuthRefreshTokenPostWithHttpInfo(refreshTokenReq);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LoginRes</returns>
        public profile.wire.Client.ApiResponse<LoginRes> UserAuthRefreshTokenPostWithHttpInfo(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0)
        {
            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = refreshTokenReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthRefreshTokenPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LoginRes>("/UserAuth/RefreshToken", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthRefreshTokenPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginRes</returns>
        public async System.Threading.Tasks.Task<LoginRes> UserAuthRefreshTokenPostAsync(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            profile.wire.Client.ApiResponse<LoginRes> localVarResponse = await UserAuthRefreshTokenPostWithHttpInfoAsync(refreshTokenReq, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="refreshTokenReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginRes)</returns>
        public async System.Threading.Tasks.Task<profile.wire.Client.ApiResponse<LoginRes>> UserAuthRefreshTokenPostWithHttpInfoAsync(RefreshTokenReq? refreshTokenReq = default(RefreshTokenReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = refreshTokenReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthRefreshTokenPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<LoginRes>("/UserAuth/RefreshToken", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthRefreshTokenPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userRegisterReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LoginRes</returns>
        public LoginRes UserAuthRegisterPost(UserRegisterReq? userRegisterReq = default(UserRegisterReq?), int operationIndex = 0)
        {
            profile.wire.Client.ApiResponse<LoginRes> localVarResponse = UserAuthRegisterPostWithHttpInfo(userRegisterReq);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userRegisterReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LoginRes</returns>
        public profile.wire.Client.ApiResponse<LoginRes> UserAuthRegisterPostWithHttpInfo(UserRegisterReq? userRegisterReq = default(UserRegisterReq?), int operationIndex = 0)
        {
            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = userRegisterReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthRegisterPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LoginRes>("/UserAuth/Register", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthRegisterPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userRegisterReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LoginRes</returns>
        public async System.Threading.Tasks.Task<LoginRes> UserAuthRegisterPostAsync(UserRegisterReq? userRegisterReq = default(UserRegisterReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            profile.wire.Client.ApiResponse<LoginRes> localVarResponse = await UserAuthRegisterPostWithHttpInfoAsync(userRegisterReq, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="profile.wire.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userRegisterReq"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LoginRes)</returns>
        public async System.Threading.Tasks.Task<profile.wire.Client.ApiResponse<LoginRes>> UserAuthRegisterPostWithHttpInfoAsync(UserRegisterReq? userRegisterReq = default(UserRegisterReq?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            profile.wire.Client.RequestOptions localVarRequestOptions = new profile.wire.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = profile.wire.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = profile.wire.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = userRegisterReq;

            localVarRequestOptions.Operation = "UserAuthApi.UserAuthRegisterPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<LoginRes>("/UserAuth/Register", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserAuthRegisterPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
